# dbt Profiles Configuration
# Copy this file to ~/.dbt/profiles.yml

financial_sentiment:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'mlops_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'mlops_secure_password_123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'mlops_warehouse') }}"
      schema: warehouse
      threads: 4
    
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: warehouse
      threads: 8
